site_name: RISo Docs
theme:
  name: material
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.top
    - navigation.tracking

extra_css:
  - stylesheets/styles.css

nav:
  - Início: index.md
  - Sobre a Facção:
    - Historia da Facção: sections/faccao/faccao.md
    - Integrantes: sections/faccao/integrantes.md
  - Visão do Produto e Projeto:
    - Visão Geral do Produto: sections/visaoProduto/visao_produto/visao_produto.md
    - Visão Geral do Projeto: sections/visaoProduto/visao_projeto/visao_projeto.md
    - Processo de Desenvolvimento de Software: sections/visaoProduto/processo_desenv/processo_desenv.md
    - Lições Aprendidas: sections/visaoProduto/licoesAprendidas/licoesAprendidas.md
    - Referência Bibliográfica: sections/visaoProduto/referencia_bibliografica.md
    - Histórico de Versão: sections/visaoProduto/historico_versao.md
  - Ciclos:
    - Planejamento Geral dos Ciclos: sections/ciclos/planejamento.md
    - Ciclo 1: sections/ciclos/ciclo1.md
    - Ciclo 2: sections/ciclos/ciclo2.md
    - Ciclo 3: sections/ciclos/ciclo3.md
    - Ciclo 4: sections/ciclos/ciclo4.md
    - Ciclo 5: sections/ciclos/ciclo5.md
    - Ciclo 6: sections/ciclos/ciclo6.md
    - Ciclo 7: sections/ciclos/ciclo7.md
  - Entregas:
    - Unidade 1:
      - Missão 1 | Apresentação: sections/entregas/unidade1/apresentacao1.md
      - Missão 1 | Video de Apresentação: sections/entregas/unidade1/video.md
    - Unidade 2:
      - Missão 2 | Backlog: sections/entregas/unidade2/apresentacao2.md
      - Missão 2 | Video de Apresentação: sections/entregas/unidade2/video.md
    - Unidade 3:
      - Missão 3 | PPB: sections/entregas/unidade3/pbb.md
      - Missão 3 | USM: sections/entregas/unidade3/usm.md
      - Verificação e Validação Fornecidas:
        - Missão 4 | PBB - Verificação e Validação à CalorieExplorer: sections/entregas/unidade3/VeriVal_Fornecidas/VeriVal-PBB-CalorieExplorer.md
        - Missão 4 | USM - Verificação e Validação à CalorieExplorer: sections/entregas/unidade3/VeriVal_Fornecidas/VeriVal-USM-CalorieExplorer.md
  - Backlog do Produto:
    - Funcionalidades: sections/historiasUsuarios/US.md
  - Políticas:
    - GSC: sections/politicas/GCS/GCS.md
    
