site_name: RISo Docs
theme:
  name: material
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.top
    - navigation.tracking

extra_css:
  - stylesheets/styles.css

nav:
  - Início: index.md
  - Sobre a Facção:
    - Historia da Facção: sections/faccao/faccao.md
    - Integrantes: sections/faccao/integrantes.md
  - Visão do Produto e Projeto:
    - Visão Geral do Produto: sections/visaoProduto/visao_produto/visao_produto.md
    - Visão Geral do Projeto: sections/visaoProduto/visao_projeto/visao_projeto.md
    - Processo de Desenvolvimento de Software: sections/visaoProduto/processo_desenv/processo_desenv.md
    - Referência Bibliográfica: sections/visaoProduto/referencia_bibliografica.md
    - Histórico de Versão: sections/visaoProduto/historico_versao.md
  - Entregas:
    - Unidade 1:
      - Missão 1 | Apresentação: sections/apresentacao/apresentacao1.md
      - Missão 1 | Video de Apresentação: sections/apresentacao/video.md