site_name: RISo Docs
theme:
  name: material
  

extra_css:
  - stylesheets/styles.css


nav:
  - Sobre: index.md
  - Sobre a faccao:
    - Historia da faccao: Faccao/faccao.md
    - Integrantes: Faccao/integrantes.md
  - Documentação: documentacao/visao-produto-projeto.md
