site_name: RISo Docs
theme:
  name: material

extra_css:
  - stylesheets/styles.css


nav:
  - Sobre: index.md
  - Sobre a Facção:
    - Historia da Facção: Faccao/faccao.md
    - Integrantes: Faccao/integrantes.md
  - Visão do Produto e Projeto:
    - Visão Geral do Produto: documentacao/visao_produto/visao_produto.md
    - Visão Geral do Projeto: documentacao/visao_projeto/visao_projeto.md
    - Processo de Desenvolvimento de Software: documentacao/processo_desenv/processo_desenv.md
    - Lições Aprendidas: documentacao/licoes_aprendidas/licoes_aprendidas.md
    - A Melhorar: documentacao/a_melhorar.md
    - Referência Bibliográfica: documentacao/referencia_bibliografica.md
    - Histórico de Versão: documentacao/historico_versao.md