name: Nova Documentação
description: Registre uma nova atividade envolvendo Documentação do projeto RISO
title: "[DOC]: <Título BREVE da Atividade>"
labels: ["documentation"]
body:
  - type: textarea
    id: text-zone1
    attributes:
      label: Descreva o que deve ser feito nesta seção da documentação.
      description: Descreva aqui os detalhes do que deverá ser escrito na documentação.
    validations:
      required: true
  - type: textarea
    id: text-zone3
    attributes:
      label: Detalhes adicionais?
      description: Escreve se houver detalhes necessários de estar à conhecimento de todos.
      placeholder: |
        Escreva ou deixe em branco.
