name: Deploy MkDocs

on:
  push:
    branches:
      - main  # ou sua branch padrão
      - DOCS-git_pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Escolha a versão do Python que você usa

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs-material

    - name: Build and deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
